config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  get 'results', to: 'loans#results', as: 'results'
  get 'wallet', to: 'users#wallet', as: "wallet"
  patch 'add_in_wallet', to: 'users#add_in_wallet', as: 'recharge'
  patch 'subtract_wallet', to: 'users#subtract_wallet', as: 'subtract_wallet'
  patch 'become_lender', to: 'users#become_lender'

  resources :loans do
    resources :contracts, only: [:index, :new, :create]
  end

  resources :contracts, only: [:show, :edit, :update] do
    patch 'repaid_loan', to: "contracts#repaid_loan"
    patch 'approve', to: "contracts#approve"
    patch 'repaid_lender', to: "contracts#repaid_lender"
    patch 'rejected', to: "contracts#rejected"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contracts
  has_many :loans
  has_many :loan_contracts, through: :loans, source: :contracts
  has_one_attached :photo

  validates :first_name, :last_name, presence: true
  validates :wallet, numericality: { only_integer: true }

  def has_loan?
    self.contracts.where(repaid_loan: true).empty?
  end

  def become_lender!
    self.lender = true
    self.save
  end

  def money_available
    total_amount = loans.joins(:contracts).where('repaid_loan = false AND approved = true').sum(&:amount)
    self.wallet - total_amount
  end

  # def substract_approved(loan)
  #   self.wallet - loan.amount
  #   self.save
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @contracts = (current_user.lender ? current_user.loan_contracts : current_user.contracts).order(:due_date)
    @loans = current_user.loans
    @pending = @contracts.where(approved: false, rejected: false)
    @completed = @contracts.where(repaid_loan: true)
    @paid = @contracts.where(repaid_lender: true, repaid_loan: false)
    #Add by Adil
    @borrower_active = @contracts.where(approved: true, repaid_lender: false)
    @borrower_history = @contracts.where(repaid_lender:true)
    authorize @contracts
  end

  def add_in_wallet
    authorize current_user
    new_wallet = user_params[:wallet].to_i + user_params[:old_wallet].to_i
    current_user.update(wallet: new_wallet)
    redirect_to dashboard_path
  end

  # def subtract_wallet
  #   authorize current_user
  #   new_wallet = user_params[:wallet].to_i - user_params[:old_wallet].to_i
  #   current_user.update(wallet: new_wallet)
  #   redirect_to dashboard_path
  # end

  def wallet
    authorize current_user
  end

  def become_lender
    authorize current_user
    current_user.become_lender!
    redirect_to dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:wallet, :old_wallet)
  end

end

app/views/users/_active-loan.html.erb
<% unless @borrower_active.empty? %>
  <div class="container">
    <div class="my-5">
      <h2>Active Loan</h2>
    </div>
    <% @contracts.where(repaid_lender: false, approved: true).each do |active_loan| %>
      <button type="button" class='card loan loan-active' data-toggle="collapse" data-target="#a-<%= active_loan.id %>" aria-expanded="false" aria-controls="<%= active_loan.id %>">
        <%= render "users/loan-card", contract: active_loan %>
      </button>
      <!-- collapsing function   -->
      <div class="collapse" id="a-<%= active_loan.id %>">
        <div class="contract-content">
          <%= render "users/loan-dropdown", pending_loan: active_loan %>
        </div>
      </div>
      <!-- / collapsing function     -->
    <% end %>
  </div>
<% end %>

app/views/users/_all-loan-table.html.erb
<% if @contracts.empty? %>
  <div class="card loan">
    <h2>You don't have any loans..</h2>
  </div>
<% else %>
  <div class="container">
    <div class="my-5">
      <h2>My Loans</h2>
    </div>
    <% @contracts.each do |contract| %>
      <% pending = !contract.approved %>
      <% active = !contract.repaid_lender && !contract.repaid_loan %>
      <% paid_loan = contract.repaid_lender && !contract.repaid_loan %>
      <% loan_class = "" %>
      <% if pending %>
        <% loan_class = "loan-pending" %>
      <% elsif active %>
        <% loan_class = "loan-active" %>
      <% elsif paid_loan %>
        <% loan_class = "loan-active" %>
      <% else %>
        <% loan_class = "loan" %>
      <% end %>
      <button class="card loan <%= "#{loan_class}" %> " data-toggle="collapse" data-target="#all-<%= contract.id %>" aria-expanded="false" aria-controls="<%= contract.id %>">
        <%= render "users/loan-card", contract: contract %>
      </button>
      <div class="collapse" id="all-<%= contract.id %>">
        <div class="contract-content">
          <%= render "users/loan-dropdown", pending_loan: contract %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_charge_form.html.erb
<%= simple_form_for current_user, url: recharge_path  do |f| %>
  <div class="form-inline loan-form-inline my-5">
    <h3 class="m-auto">Your wallet balance is <%= number_to_currency(current_user.money_available, unit: '￥', precision: 0) %></h3>
  </div>
  <div class="form-inline loan-form-inline">
    <%= f.label :wallet, "Amount:" %>
    <div class="input-icon">
      <%= f.input :wallet, input_html: {min: 10000, max: 200000, step: 10000}, label: "Amount", placeholder: "0", class: "loan-input loan-amount", label: false%>
      <%= f.input :old_wallet, as: :hidden, input_html: { value: current_user.wallet } %>
      <i>￥</i>
    </div>
  </div>
  <%= f.button :submit, class: "btn btn-approve w-100" %>
<% end %>

app/views/users/_loan-approval-buttons.html.erb
<div class='approval-buttons'>
  <h5>Approve?</h5>
  <%= link_to contract_approve_path(pending_loan), method: "patch" , class: "btn btn-approve btn-circle m-0 p-0" do  %>
  <!-- SUBTRACT APPROVED CONTRACT FROM WALLET -->
    <i class="fas fa-check-circle"></i>
  <% end %>
  <%= link_to contract_rejected_path(pending_loan), method: "patch" , class: "btn btn-reject btn-circle m-0 p-0"  do %>
    <i class="fas fa-times-circle"></i>
  <% end %>
</div>

app/views/users/_loan-card.html.erb
<% status = "" %>
<% if current_user.lender %>
  <% name = "#{contract.user.first_name} #{contract.user.last_name[0]}." %>
  <% status_paid = "has sent payment for"  %>
  <% if contract.approved == false %>
    <% status = " wants to borrow" %>
  <% elsif contract.repaid_loan %>
    <% status = " borrowed" %>
  <% elsif contract.rejected %>
    <% status = " was rejected ->" %>
  <% else %>
    <% status = " is borrowing" %>
  <% end %>
<% else %>
  <% name = "You" %>
  <% status_paid = "have paid back"  %>
  <% if contract.approved == false %>
    <% status = " requested to borrow" %>
  <% elsif contract.repaid_loan %>
    <% status = " borrowed" %>
  <% elsif contract.rejected %>
    <% status = " were rejected ->" %>
  <% else %>
    <% status = " are borrowing" %>
  <% end %>
<% end %>
<% if contract.repaid_lender %>
  <div class="contract-amount">
    <p><%= name %> <%= status_paid %> ￥<%= contract.loan.amount %> </p>
    <i class="fas fa-ellipsis-v"></i>
  </div>
<% else %>
  <div class="contract-amount">
    <p><%= name %> <%= status %> ￥<%= contract.loan.amount %> over <%= contract.loan.duration %> days.</p>
    <i class="fas fa-ellipsis-v"></i>
  </div>
<% end %>

app/views/users/_loan-dropdown.html.erb
<div class="container loan-dropdown">
  <div class="row justify-content-center">
    <div class="sm-col-2 col-12">
      <h5>Reason for loan: <%= pending_loan.description %></h5>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="sm-col-2 col-6">
      <p>Borrower: <%= pending_loan.user.first_name %> <%= pending_loan.user.last_name[0] %>.</p>
    </div>
    <div class="sm-col-4 col-6">
      <% total = pending_loan.loan.amount + ((pending_loan.loan.amount * pending_loan.loan.interest_rate)/ 100).round %>
      <h4>Total amount: <%= number_to_currency(total, unit: '￥', precision: 0) %></h4>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="sm-col-2 col-6">
      <p> Interest: <%= pending_loan.loan.interest_rate %> %</p>
    </div>
    <div class="sm-col-4 col-6">
      <h4>Due: <%= pending_loan.loan.duration.days.since.strftime("%b %e") %></h4>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="sm-col-4 col-6">
      <% if policy(pending_loan).approve? %>
        <% if !pending_loan.approved %>
          <%= render "users/loan-approval-buttons", pending_loan: pending_loan  %>
          <!-- SUBTRACT APPROVED CONTRACT FROM WALLET -->
        <% elsif pending_loan.repaid_lender && !pending_loan.repaid_loan%>
          <%= render "users/loan-paid-buttons", pending_loan: pending_loan  %>
        <% end %>
      <% end %>
      <% if !pending_loan.repaid_lender && !current_user.lender && pending_loan.approved %>
        <%= render "users/loan-repay-buttons", pending_loan: pending_loan  %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_loan-header.html.erb
<div class="contract-id">
  <p>Loan ID</p>
</div>
<div class="contract-amount">
  <p>Amount</p>
</div>
<div class="contract-interest">
  <p>Interest Rate</p>
</div>
<div class="contract-total">
  <p>Total Amount</p>
</div>
<div class="contract-due">
  <p>Due</p>
</div>

app/views/users/_loan-paid-buttons.html.erb
<div class='approval-buttons'>
  <h5>Loan repaid?</h5>
  <%= link_to contract_repaid_loan_path(pending_loan), method: "patch" , class: "btn btn-approve btn-circle m-0 p-0" do  %>
    <i class="fas fa-check-circle"></i>
  <% end %>
  <%= link_to "#", method: "patch" , class: "btn btn-reject btn-circle m-0 p-0"  do %>
    <i class="fas fa-times-circle"></i>
  <% end %>
</div>

app/views/users/_loan-repay-buttons.html.erb
<div class='approval-buttons'>
  <h5>Repay loan?</h5>
  <%= link_to contract_repaid_lender_path(pending_loan), method: "patch" , class: "btn btn-approve btn-circle m-0 p-0" do  %>
    <i class="fas fa-check-circle"></i>
  <% end %>
</div>

app/views/users/_payment-confirm-loan-table.html.erb
<% unless @paid.empty? %>
  <div class="container">
    <div class="my-5">
      <h2>Confirm Repayment</h2>
    </div>
    <% @paid.each do |pending_loan| %>
      <button type="button" class='card loan loan-paid' data-toggle="collapse" data-target="#a-<%= pending_loan.id %>" aria-expanded="false" aria-controls="<%= pending_loan.id %>">
        <%= render "users/loan-card", contract: pending_loan %>
      </button>
      <!-- collapsing function   -->
      <div class="collapse" id="a-<%= pending_loan.id %>">
        <div class="contract-content">
          <%= render "users/loan-dropdown", pending_loan: pending_loan %>
        </div>
      </div>
      <!-- / collapsing function     -->
    <% end %>
  </div>
<% end %>

app/views/users/_pending-loan-table.html.erb
<% unless @pending.empty? %>
  <div class="container">
    <div class="my-5">
      <h2>Pending approval</h2>
    </div>
    <% @pending.each do |pending_loan| %>
      <button type="button" class='card loan loan-pending' data-toggle="collapse" data-target="#a-<%= pending_loan.id %>" aria-expanded="false" aria-controls="<%= pending_loan.id %>">
        <%= render "users/loan-card", contract: pending_loan %>
      </button>
      <!-- collapsing function   -->
      <div class="collapse" id="a-<%= pending_loan.id %>">
        <div class="contract-content">
          <%= render "users/loan-dropdown", pending_loan: pending_loan %>
        </div>
      </div>
      <!-- / collapsing function     -->
    <% end %>
</div>
<% end %>

app/views/users/_sidebar.html.erb
<div class="sidenav">
  <% if current_user.lender %>
    <p class= "wallet">
      <%= link_to wallet_path do %>
        <i class="fas fa-wallet">+</i>
      <% end %>
      <span id='wallet'> <%= number_to_currency(current_user.money_available, unit: '￥', precision: 0) %> </span>
    </p>
    <%= link_to "Offer a Loan", new_loan_path, class: "btn btn-new-loan"  %>
  <% end %>
</div>

app/views/users/dashboard.html.erb
  <% if current_user.lender %>
  <%= render "sidebar" %>
  <div class="contract-wrapper">
    <!-- payment-confirm loan table -->
    <%= render "payment-confirm-loan-table" %>
    <!-- /payment-confirm loan table -->
    <!-- pending loan table -->
    <%= render "pending-loan-table" %>
    <!-- / pending loan table -->
  <% else %>
    <div class="contract-wrapper">
      <!-- active contracts table -->
      <%= render "pending-loan-table" %>
      <%= render "active-loan" %>
      <!-- / active contracts table -->
    <% end %>
    <!-- all contracts table -->
    <%= render "all-loan-table" %>
    <!--  removed for presentation -->
    <!-- / all contracts table -->
    <%# if policy(current_user).become_lender? %>
    <!-- #link_to "become a lender", become_lender_path, class: "btn btn-primary m-5", method: 'patch' %> -->
    <!-- #else  -->
    <!--  <p class='btn btn-secondary'>Become lender</p> -->
    <%# end %>
  </div>

app/views/users/wallet.html.erb
<div class="container form-container">
  <h1> Recharge your balance</h1>
  <div class="loan-form">
    <%= render 'charge_form' %>
  </div>
</div>