config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  get 'results', to: 'loans#results', as: 'results'
  get 'wallet', to: 'users#wallet', as: "wallet"
  patch 'add_in_wallet', to: 'users#add_in_wallet', as: 'recharge'
  patch 'subtract_wallet', to: 'users#subtract_wallet', as: 'subtract_wallet'
  patch 'become_lender', to: 'users#become_lender'

  resources :loans do
    resources :contracts, only: [:index, :new, :create]
  end

  resources :contracts, only: [:show, :edit, :update] do
    patch 'repaid_loan', to: "contracts#repaid_loan"
    patch 'approve', to: "contracts#approve"
    patch 'repaid_lender', to: "contracts#repaid_lender"
    patch 'rejected', to: "contracts#rejected"
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light-blue footer">
  <div class="footer-links">
    <a href="https://github.com/AdilOmary" target="_blank"  title="Adil Omary" data-toggle="popover" data-trigger="hover" data-content="Project Manager"><%= image_tag "https://avatars1.githubusercontent.com/u/59479470?s=460&v=4", alt: "Adil's image", class: "avatar-bordered" %></a>
    <a href="https://github.com/rnd00" target="_blank" title="Ryanda Diedan" data-toggle="popover" data-trigger="hover" data-content="Lead Developer"><%= image_tag "https://avatars2.githubusercontent.com/u/42826652?s=460&v=4", alt: "Ryanda's image", class: "avatar-bordered" %></a>
    <a href="https://github.com/toadslop" target="_blank" title="Brian Heise" data-toggle="popover" data-trigger="hover" data-content="Back-end"><%= image_tag "https://avatars2.githubusercontent.com/u/31160338?s=460&v=4", alt: "Brian's image", class: "avatar-bordered" %></a>
    <a href="https://github.com/Gakkun89" target="_blank"title="Mike Warren" data-toggle="popover" data-trigger="hover" data-content="Front-end"><%= image_tag "https://avatars0.githubusercontent.com/u/28691463?s=460&v=4", alt: "Mike's image", class: "avatar-bordered" %></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon Tokyo by Team Bokkun
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-logo">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
      <% if current_user && current_user.lender %>
        <p class="logo-text"> Kinzame-Lend</p>
      <% elsif current_user %>
        <p class="logo-text"> Kinzame-Borrow</p>
      <% else %>
        <p class="logo-text"> Kinzame</p>
      <% end %>
    <% end %>
  </div>
  <!-- TODO Change below logic to check if current user -->
  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% unless current_user.lender %>
        <div class="d-flex flex-row my-3 mx-auto">
          <%= form_tag results_path, class: 'form-inline mx-auto', method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control search-bar-navbar",
              placeholder: "Search loan.."
            %>
            <%= button_tag(type: "submit", class: "btn btn-blocky btn-approve mx-3") do %>
              <i class="fas fa-yen-sign"></i>
            <% end %>
          <% end %>
        </div>
        <%= link_to "Become a Lender", become_lender_path, class: "btn btn-primary mx-5", method: 'patch' %>
      <% end %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <i class="fas fa-bars dropdown-toggle navbar-burger" id="navbarDropdown" data-toggle="dropdown" ></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="navbar-login">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Login/Sign up", new_user_session_path, class: "btn btn-primary text-white" %>
        </li>
      </ul>
    </div>
  <% end %>
</div>