config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  get 'results', to: 'loans#results', as: 'results'
  get 'wallet', to: 'users#wallet', as: "wallet"
  patch 'add_in_wallet', to: 'users#add_in_wallet', as: 'recharge'
  patch 'subtract_wallet', to: 'users#subtract_wallet', as: 'subtract_wallet'
  patch 'become_lender', to: 'users#become_lender'

  resources :loans do
    resources :contracts, only: [:index, :new, :create]
  end

  resources :contracts, only: [:show, :edit, :update] do
    patch 'repaid_loan', to: "contracts#repaid_loan"
    patch 'approve', to: "contracts#approve"
    patch 'repaid_lender', to: "contracts#repaid_lender"
    patch 'rejected', to: "contracts#rejected"
  end
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  has_many :contracts

  validates :amount, :interest_rate, :duration, presence: true
  validates :duration, numericality: { only_integer: true }
  validates :amount, numericality: { only_integer: true, less_than_or_equal_to: 100000}
  validates :interest_rate, numericality: { less_than_or_equal_to: 10 }

  include PgSearch::Model
  pg_search_scope :search_by_amount,
    against: [ :amount],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i(show edit update destroy)
  skip_before_action :authenticate_user!, only: %i(index show results)

  def index
    @loans = policy_scope(Loan)
    #but only for the user when pundit will be install
  end

  def results
    @loans = Loan.where.not(user: current_user)
    @loans = @loans.joins(:user).where("wallet - amount >= 0")
    if params[:query].present?
      bottom = params[:query].to_i - 10000
      top = params[:query].to_i + 10000
      @loans = @loans.where("amount >= #{bottom} AND amount <= #{top}")
      authorize @loans
    else
      @loans
      authorize @loans
    end
  end

  def show
    authorize @loan
  end

  def new
    @loan = Loan.new
    authorize @loan
  end

  def create
    @loan = Loan.new(loan_params)
    authorize @loan
    @loan.user = current_user
    if @loan.save
      redirect_to loan_path(@loan)
    else
      render :new
    end
  end

  def edit
    authorize @loan
  end

  def update
    authorize @loan
    if @loan.update(loan_params)
      redirect_to loan_path(@loan)
    else
      render :edit
    end
  end

  def accepted
    loan = find_loan
    loan.accepted = true
    loan.save!
    redirect_to loan_path(@loan)
  end

  def declined
    loan = find_loan
    loan.accepted = false
    loan.save!
    redirect_to loans_path
  end

  def destroy
    authorize @loan
    @loan.destroy
    redirect_to loans_path
  end

  private

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:due_date, :amount, :duration, :interest_rate)
  end

end

app/views/loans/_form.html.erb
<%= simple_form_for @loan do |f| %>
  <div class="form-inline loan-form-inline my-5">
    <h3 class="m-auto">Your wallet balance is <%= "#{number_to_currency(@current_user.wallet, unit: "￥", precision: 0)}" %></h3>
  </div>
  <div class="form-inline loan-form-inline">
    <%= f.label :amount, "Amount:" %>
    <div class="input-icon">
      <%= f.input :amount, input_html: {min: 10000, max: @current_user.wallet, step: 10000}, label: "Amount", placeholder: "10000", class: "loan-input loan-amount", label: false%>
      <i>￥</i>
    </div>
  </div>
  <% if @current_user.wallet >= 10000 %>
    <p class="amount-details">(The maximum amount is <%= "#{number_to_currency(@current_user.wallet, unit: "￥", precision: 0)}" %>)</p>
  <% end %>
  <div class="form-inline loan-form-inline">
    <%= f.label :duration, "Duration (days):" %>
    <%= f.input :duration, collection: [7, 14, 30, 60, 90], label: "Duration (days)", include_blank: false, label: false, class: "loan-input loan-duration" %>
  </div>
  <div class="form-inline loan-form-inline">
    <%= f.label :interest_rate, "Interest rate:" %>
    <div class="input-icon input-icon-right">
      <%= f.input :interest_rate, input_html: {min: 0.0, max: 10.5, step: 0.1}, placeholder: "0.0", class: "loan-input loan-rate", label: false%>
      <i>%</i>
    </div>
  </div>
  <div <%= "hidden" unless @current_user.wallet >=10000 %>>
    <%= f.button :submit, class: "btn btn-approve w-100" %>
  </div>
<% end %>

app/views/loans/charge_wallet.html.erb
<div class="container form-container">
  <h1> Recharge your balance</h1>
  <div class="loan-form">
    <%= render 'charge_form' %>
  </div>
</div>

app/views/loans/edit.html.erb
<h1>Loan Edit Page</h1>
<%= render 'form' %>

app/views/loans/index.html.erb
<h1>Loans index</h1>
<% @loans.each do |loan| %>
  <p>Lender name:</p> <%= loan.user.first_name %>
<% end %>

app/views/loans/new.html.erb
<div class="container form-container">
  <h1>Offer a new type of loan</h1>
  <div class="loan-form">
    <%= render 'form' %>
  </div>
</div>

app/views/loans/results.html.erb
<div class="container">
  <h1 class="text-center" id="search-result-title">Search results for Loans of <%= number_to_currency(params[:query], unit: "￥", precision: 0) %></h1>
  <div class="card-columns my-5">
    <% @loans.each do |loan| %>
      <%# codes  %>
      <% total_amt = (loan.amount + (loan.amount * loan.interest_rate / 100)).round %>
      <% due_until = loan.duration.days.since.strftime("%b %e") %>
      <% due_days_count = loan.duration %>
      <%# / codes  %>
      <%# if !user_signed_in? || policy(Contract).create? %>
        <%= link_to new_loan_contract_path(loan_id: loan.id) do %>
          <div class="card card-body text-center" id="card-search-loan">
            <h3 class="card-title"><%= "#{number_to_currency(total_amt, unit: "￥", precision: 0)}" %></h3>
            <p>Amount: <%= "#{number_to_currency(loan.amount, unit: "￥", precision: 0)}" %></p>
            <p>Interest: <%= loan.interest_rate %>%</p>
            <p>Due on: <%= "#{due_until} (#{due_days_count} days)" %></p>
            <!-- <p>Lender: <%= loan.user.first_name %></p> -->
          </div>
        <% end %>
      <%# else %>
        <!--< div class="card card-body text-center" id="card-search-loan">
          <h3 class="card-title"><%= "#{number_to_currency(total_amt, unit: "￥", precision: 0)}" %></h3>
          <p>Amount: <%= "#{number_to_currency(loan.amount, unit: "￥", precision: 0)}" %></p>
          <p>Interest: <%= loan.interest_rate %>%</p>
          <p>Due on: <%= "#{due_until} (#{due_days_count} days)" %></p>
        < /div>-->
      <%# end %>
    <% end %>
  </div>
</div>

app/views/loans/show.html.erb
<div class="container">
  <div class="loan-container w-50">
    <h1 class="text-center m-5">Loan # <%= @loan.id %></h1>
    <div class="card p-5 w-75 mx-auto">
      <h3 class="card-title text-center"><%= "#{number_to_currency(@loan.amount, unit: "￥", precision: 0)}" %></h3>
      <p>Interest Rate: <%= @loan.interest_rate %>%</p>
      <p>Duration: <%= @loan.duration %> Days</p>
      <p>Potential return: ￥<%=
          (@loan.amount + ( @loan.amount * @loan.interest_rate / 100 )).round
          %></p>
      <%= link_to "Dashboard", dashboard_path, class: "btn btn-main w-100"  %>
    </div>
  </div>
</div>